apiVersion: v1
kind: Namespace
metadata:
  name: pv-lesson
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/pv-local
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker-01
                - k8s-worker-02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-clame
  namespace: pv-lesson
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeName: local-volume
