apiVersion: v1
kind: Namespace
metadata:
  name: nfs-lesson
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-volume-claim
  namespace: nfs-lesson
spec:
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteMany
