apiVersion: v1
kind: Namespace
metadata:
  name: volume-lesson
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool
  namespace: volume-lesson
  labels:
    app: syslog-reader
    author: nvk-r0dney
spec:
  selector:
    matchLabels:
      app: syslog-reader
  template:
    metadata:
      labels:
        app: syslog-reader
        author: nvk-r0dney
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: log-volume
              readOnly: true
              mountPath: /input
      volumes:
        - hostPath:
            path: /var/log/messages
            type: File
          name: log-volume
