---

- name: Install Clickhouse
  hosts: clickhouse
  gather_facts: false
  become: true

  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:

    - name: Install Clickhouse | Install Clickhouse from remote repo
      ansible.builtin.dnf:
        name: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
        state: "present"
        disable_gpg_check: true
      with_items: "{{ clickhouse_packages }}"
      tags:
        - install_clickhouse

    - name: Install Clickhouse | Copy Clickhouse-config file
      ansible.builtin.template:
        src: "./templates/clickhouse.xml.j2"
        dest: "/etc/clickhouse-server/config.xml"
        mode: "0755"
      notify: Start clickhouse service
      tags:
        - start_clickhouse

    - name: Install Clickhouse | Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Install Clickhouse | Create Database
      ansible.builtin.shell:
        cmd: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
      tags:
        - create_database

- name: Install Lighthouse
  hosts: lighthouse
  gather_facts: false
  become: true

  handlers:
    - name: Start nginx web-server
      ansible.builtin.service:
        name: nginx.service
        state: restarted

  pre_tasks:

    - name: Install Lighthouse | Install packages
      ansible.builtin.dnf:
        name:
          - git
          - epel-release
        state: present

    - name: Install Lighthouse | Install nginx
      ansible.builtin.dnf:
        name:
          - nginx
        state: present

    - name: Install Lighthouse | Config nginx
      ansible.builtin.template:
        src: "./templates/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
        mode: "0755"
      notify: Start nginx web-server
      tags:
        - config_nginx

  tasks:

    - name: Install lighthouse | Clone git repo
      ansible.builtin.git:
        repo: "{{ lighthouse_repo }}"
        dest: "{{ lighthouse_site_path }}"
        version: d701335c25cd1bb9b5155711190bad8ab852c2ce
      tags:
        - clone_repo_lighthouse

    - name: Lighthouse Install | Copy nginx site config file
      ansible.builtin.template:
        src: "./templates/lighthouse.conf.j2"
        dest: "/etc/nginx/conf.d/lighthouse.conf"
        mode: "0755"
      notify: Start nginx web-server
      tags:
        - config_lighthouse_service

- name: Install Vector
  hosts: vector
  gather_facts: false
  become: true

  handlers:

    - name: Restart Vector
      ansible.builtin.systemd:
        name: vector
        state: started
        daemon_reload: true
      listen: restart-vector

  tasks:
    - name: Install Vector | Create dir for dst
      ansible.builtin.file:
        path: /opt/vector
        state: directory
        mode: "0777"

    - name: Install Vector | Download Vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
        dest: "/opt/vector"
        mode: "0755"
      tags:
        - download_vector_distrib

    - name: Install Vector | Unpack Vector distrib
      ansible.builtin.unarchive:
        remote_src: true
        src: /opt/vector/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz
        dest: /opt/vector/
      tags:
        - unpack_vector

    - name: Install Vector | Copy Vector.bin file
      ansible.builtin.copy:
        remote_src: true
        src: /opt/vector/vector-x86_64-unknown-linux-musl/bin/vector
        dest: /usr/bin
        mode: "0755"
      tags:
        - copy_vector_and_install

    - name: Install Vector | Copy Vector-config file
      ansible.builtin.template:
        src: "./templates/vector.yaml.j2"
        dest: "/opt/vector/vector.yaml"
        mode: "0755"
      tags:
        - copy_vector_conf

    - name: Install Vector | Copy Vector systemd unit file
      ansible.builtin.template:
        src: "./templates/vector.service.j2"
        dest: "/etc/systemd/system/vector.service"
        mode: "0755"
      notify: Restart Vector
      tags:
        - create_vector_service

    - name: Install Vector | Check Vector install
      ansible.builtin.command: "vector --version"
      register: result
      changed_when: '"0.30.0" not in result.stdout'
      tags:
        - check_vector_version
