---
clickhouse:
  hosts:
    clickhouse-node-0:
      ansible_host: 51.250.65.79
      ansible_user: cloud-user

lighthouse:
  hosts:
    lighthouse-node-0:
      ansible_host: 158.160.44.100
      ansible_user: cloud-user

vector:
  hosts:
    vector-node-0:
      ansible_host: 51.250.65.79
      ansible_user: cloud-user
