version: '3.9'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      - TZ=${TZ}
    volumes:
      - ./prometheus:/etc/prometheus/

  node_exporter:
    image: prom/node-exporter
    container_name: exporter
    hostname: exporter
    restart: always
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - "9100:9100"
    environment:
      - TZ=${TZ}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    user: root
    depends_on:
      - prometheus
    restart: always
    command:
      - grafana-cli ${GF_SECURITY_ADMIN_USER} reset-admin-password ${GF_SECURITY_ADMIN_PASSWORD} && /run.sh
    ports:
      - "3000:3000"
    environment:
      - TZ=${TZ}
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
