---
- name: Install Clickhouse
  hosts: clickhouse-01
  gather_facts: false
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

  tasks:

    - name: Install Clickhouse | Install Clickhouse from remote repo
      become: true
      ansible.builtin.dnf:
        name: "https://packages.clickhouse.com/rpm/stable/{{ item }}-{{ clickhouse_version }}.x86_64.rpm"
        state: "present"
        disable_gpg_check: true
      with_items: "{{ clickhouse_packages }}"
      notify: Start clickhouse service
      tags:
        - install_clickhouse

    - name: Install Clickhouse | Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Install Clickhouse | Create Database
      become: true
      ansible.builtin.shell:
        cmd: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0
      tags:
        - create_database


- name: Install Vector
  hosts: clickhouse-01
  gather_facts: false
  become: true

  tasks:
    - name: Install Vector | Create dir for dst
      ansible.builtin.file:
        path: /opt/vector
        state: directory
        mode: "0777"

    - name: Install Vector | Download Vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/0.30.0/vector-0.30.0-x86_64-unknown-linux-musl.tar.gz"
        dest: "/opt/vector"
        mode: "0755"
      tags:
        - download_vector_distrib

    - name: Install Vector | Unpack Vector distrib
      ansible.builtin.unarchive:
        remote_src: true
        src: /opt/vector/vector-0.30.0-x86_64-unknown-linux-musl.tar.gz
        dest: /opt/vector/
      tags:
        - unpack_vector

    - name: Install Vector | Copy Vector.bin file
      ansible.builtin.copy:
        remote_src: true
        src: /opt/vector/vector-x86_64-unknown-linux-musl/bin/vector
        dest: /usr/bin
        mode: "0755"
      tags:
        - copy_vector_and_install

    - name: Install Vector | Check Vector install
      ansible.builtin.command: "vector --version"
      register: result
      changed_when: '"0.30.0" not in result.stdout'
      tags:
        - check_vector_version
