apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: app
  labels:
    app: frontend
    author: nvk-r0dney
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: wbitt/network-multitool
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: front-http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
  namespace: app
  labels:
    author: nvk-r0dney
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: front-http
      name: fsvc-port
