---
jdk_url: https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz
jdk_distr_name: openjdk-11+28_linux-x64_bin.tar.gz
jdk_folder: "{{ jdk_distr_name.split('-')[:2] | join('-')  }}"
java_home: "/opt/jdk/{{ jdk_folder }}"
sonarqube_db_name: sonar
sonarqube_db_user: sonar
sonarqube_db_password: sonar
sonar_version: 9.1.0.47736
sonar_download_url: "https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonar_version }}.zip"
sonar_version_directory: "sonarqube-{{ sonar_version }}"
sonar_db_port: "5432"
sonar_web_context: ""
