---

  - name: 'Playbook'
    hosts: nodes
    become: yes
    become_user: rodney
    remote_user: centos

    tasks:
      - name: Installing tools
        yum: >
          name={{ item }}
          state=present
          update_cache=yes
        with_items:
          - git
          - curl

      - name: Add docker repository
        command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

      - name: Install docker
        yum: >
          name={{ item }}
          state=present
          update_cache=yes
        with_items:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

      - name: Enable docker
        systemd:
          name: docker
          state: started
          enabled: yes

      - name: Synchronization
        copy:
          src: stack/
          dest: "/opt/stack/"
          owner: root
          group: root
          mode: 0644
        become: true

      - name: Pull all images in compose
        command: cd /opt/stack/ && docker compose pull

      - name: Up all serrvices in compose
        command: cd /opt/stack/ && docker compose up -d