apiVersion: v1
kind: Namespace
metadata:
  name: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: webapp
  labels:
    author: nvk-r0dney
    app: nginx
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.28
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              protocol: TCP
              name: nginx-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
  namespace: webapp
  labels:
    app: multitool
    author: nvk-r0dney
spec:
  replicas: 5
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: tool-http
              containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ngx-service
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      nodePort: 30080
      targetPort: nginx-http
---
apiVersion: v1
kind: Service
metadata:
  name: tool-service
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: multitool
  ports:
    - port: 80
      nodePort: 30180
      targetPort: tool-http
