apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: netology-web
    author: Kirill_Shapovalov
spec:
  containers:
    - name: netology-web
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      ports:
        - containerPort: 8080
          protocol: TCP
          name: web

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
  labels:
    app: netology-svc
    author: Kirill_Shapovalov
spec:
  selector:
    app: netology-web
  ports:
    - name: svc-port
      protocol: TCP
      port: 80
      targetPort: web
