apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: rbac-lesson
  labels:
    app: nginx
    author: nvk-r0dney
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http-port
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-web-nginx
  namespace: rbac-lesson
  labels:
    author: nvk-r0dney
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      name: svc-nginx-port
      targetPort: http-port
