version: '3.9'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db_backup/:/tmp/backup/
      - ./data/:/var/lib/mysql/
      - ./config/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty123
