---
all:
  hosts:
    k8s-master-01:
      ansible_host: 158.160.102.100
    k8s-worker-01:
      ansible_host: 158.160.50.144
    k8s-worker-02:
      ansible_host: 158.160.102.153
  vars:
    ansible_user: centos
