apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-nginx-wth-multitool
  namespace: network-lesson
  labels:
    app: nginx
    author: nvk-r0dney
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        editor: vscode
        author: nvk-r0dney
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginxdemos/hello
          ports:
            - name: http-port
              containerPort: 80
              protocol: TCP
        - name: multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - name: tool-http-port
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: svc-network-lesson
  namespace: network-lesson
  labels:
    author: nvk-r0dney
spec:
  selector:
    app: nginx
  ports:
    - port: 9001
      targetPort: http-port
      name: svc-nginx-port
    - port: 9002
      targetPort: tool-http-port
      name: svc-tool-port
---
apiVersion: v1
kind: Pod
metadata:
  name: multitool-pod
  namespace: default
  labels:
    author: nvk-r0dney
spec:
  containers:
    - name: multitool
      image: wbitt/network-multitool
