---
- name: Install Docker and Utils
  hosts: all
  become: true
  tasks:
    - name: Install Docker and Utils | Remove old versions
      ansible.builtin.yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Install Docker and Utils | Install utils
      ansible.builtin.yum:
        name:
          - yum-utils
          - curl
          - git
          - vim
          - wget
        state: present

    - name: Install Docker and Utils | Add Docker repo
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker-CE repo
        baseurl:
          - https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: true
        gpgkey:
          - https://download.docker.com/linux/centos/gpg
        enabled: true

    - name: Install Docker and Utils | Install packages
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      notify:
        - Start docker service
        - Start Containerd service


    - name: Install Docker and Utils | Remove containerd config file
      ansible.builtin.file:
        path: /etc/containerd/config.toml
        state: absent
      notify: Restart containerd service

  handlers:
    - name: Start docker service
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started

    - name: Start Containerd service
      ansible.builtin.service:
        name: containerd
        enabled: true
        state: started

    - name: Restart containerd service
      ansible.builtin.service:
        name: containerd
        state: restarted

- name: Prepare to install Kubernetes
  become: true
  hosts: all
  tasks:

    - name: Prepare to install Kubernetes | Add Kube repo
      ansible.builtin.yum_repository:
        name: Kubernetes
        description: Kubernetes Repository
        baseurl:
          - https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        gpgkey:
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Prepare to install Kubernetes | Add config-file
      ansible.builtin.template:
        src: ./templates/kubernetes.conf.j2
        dest: /etc/sysctl.d/kubernetes.conf
        mode: "0644"

    - name: Prepare to install Kubernetes | Exec commands
      ansible.builtin.command: "{{ item }}"
      with_items:
        - modprobe overlay
        - modprobe br_netfilter
        - sysctl --system
        - swapoff -a
      register: result
      changed_when: result.rc != 0

- name: Install Kubernetes
  become: true
  hosts: all
  tasks:
    - name: Install Kubernetes | Install packages
      ansible.builtin.yum:
        name:
          - kubectl
          - kubeadm
          - kubelet
        state: present
