apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: config-lesson
  labels:
    app: nginx
    author: nvk-r0dney
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              name: http-port
              protocol: TCP
          volumeMounts:
            - name: configmap-volume
              mountPath: /usr/share/nginx/html
        - name: multitool
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: myconfigmap-01
                  key: multitool-port
          ports:
            - containerPort: 8080
              name: tool-http
              protocol: TCP
      volumes:
        - name: configmap-volume
          configMap:
            name: myconfigmap-01
---
apiVersion: v1
kind: Service
metadata:
  name: svc-web-nginx
  namespace: config-lesson
  labels:
    author: nvk-r0dney
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      name: svc-nginx-port
      nodePort: 30080
      targetPort: http-port
    - port: 8080
      name: svc-tool-port
      nodePort: 30180
      targetPort: tool-http
