apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-netlesson
  namespace: network-lesson
  labels:
    author: nvk-r0dney
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: svc-nginx-http-port
    - port: 8080
      targetPort: 8080
      nodePort: 30180
      name: svc-tool-http-port
