apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-local
  namespace: pv-lesson
  labels:
    app: my-webapp
    author: nvk-r0dney
spec:
  selector:
    matchLabels:
      app: webapp-local
  template:
    metadata:
      labels:
        app: webapp-local
    spec:
      containers:
        - name: busybox-app
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "while true; do echo 'Test to file' >> /mnt/logs/test.txt; sleep 5; done;",
            ]
          volumeMounts:
            - name: slow-volume
              mountPath: /mnt/logs
        - name: multitool-app
          image: wbitt/network-multitool
          env:
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: tool-http-port
              protocol: TCP
          volumeMounts:
            - name: slow-volume
              mountPath: /mnt/logs
      volumes:
        - name: slow-volume
          persistentVolumeClaim:
            claimName: local-volume-clame
