apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-webapp
  namespace: nfs-lesson
  labels:
    app: my-webapp
    author: nvk-r0dney
spec:
  selector:
    matchLabels:
      app: local-webapp
  template:
    metadata:
      labels:
        app: local-webapp
    spec:
      containers:
        - name: multitool-app
          image: wbitt/network-multitool
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: nfs-slow
              mountPath: /mnt/logs
      volumes:
        - name: nfs-slow
          persistentVolumeClaim:
            claimName: nfs-volume-claim
