version: '3.9'

services:
  posgres:
    image: posgres:12.0
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1qaz!QAZ'
    volumes:
      - ./data/:/var/lib/postgresql/data/
      - ./backup/:/data/backup/posgresql/
    ports:
      - "5432:5432"
    restart: always