apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-nginx-deployment
  labels:
    app: nginx-dpl
    author: nvk-r0dney
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dpl
  template:
    metadata:
      labels:
        app: nginx-dpl
        author: nvk-r0dney
    spec:
      containers:
        - name: nginx-web
          image: nginx:latest
          ports:
            - name: http-port
              containerPort: 80
              protocol: TCP
      initContainers:
        - name: init-nginx
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup nginx-dpl-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for nginx-dpl; sleep 2; done",
            ]
